[[Libassuan]]
arch = "aarch64"
git-tree-sha1 = "2e19e1bf96d0f975be93e695c111ea5c0e4e06e9"
libc = "glibc"
os = "linux"

    [[Libassuan.download]]
    sha256 = "fa60f6d29f15be545e666f7d8fdc9bf79837d4aac09fe86a5fc2e4d0dfef61f5"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.aarch64-linux-gnu.tar.gz"
[[Libassuan]]
arch = "aarch64"
git-tree-sha1 = "ab1f9fe322dce52d36d47af3a16735e3f8c6b557"
libc = "musl"
os = "linux"

    [[Libassuan.download]]
    sha256 = "6211e9b5958a62100de815bc7390fa1bd43a3ba076f10ac3fa9c9952f4706081"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.aarch64-linux-musl.tar.gz"
[[Libassuan]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "18853bc090d40361810ba97824e93e806baf5c4f"
libc = "glibc"
os = "linux"

    [[Libassuan.download]]
    sha256 = "8c512c2b305e0550248baeb3b8c1f36a4f95112eb98d46ac6fe5ac1cde18a292"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.armv7l-linux-gnueabihf.tar.gz"
[[Libassuan]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2e3af492e10a53f094a95ace23a65218677e6ff"
libc = "musl"
os = "linux"

    [[Libassuan.download]]
    sha256 = "5997be29b224ad36dfebc2b523accb34c72ed578c900f141d3201827a43f52c0"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.armv7l-linux-musleabihf.tar.gz"
[[Libassuan]]
arch = "i686"
git-tree-sha1 = "06acafdd481a867e99b066bd595443e17e5397f3"
libc = "glibc"
os = "linux"

    [[Libassuan.download]]
    sha256 = "714a61ec464d3dbb78c03d84e44ccfc7f23941da76abf9cc70dfccb3a7d6a239"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.i686-linux-gnu.tar.gz"
[[Libassuan]]
arch = "i686"
git-tree-sha1 = "dd1c99c3535840eb6639bb64337f5c71c690727f"
libc = "musl"
os = "linux"

    [[Libassuan.download]]
    sha256 = "6006e24b506f8e6163717879f4088bf756ca0946313c38f735d7b4f96cca0359"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.i686-linux-musl.tar.gz"
[[Libassuan]]
arch = "i686"
git-tree-sha1 = "e6ea9aa0852137206d4c80c2140e49a641750a63"
os = "windows"

    [[Libassuan.download]]
    sha256 = "8635e5b6d894024796613c6643d684365952847941cc7e147262fb8132306f3d"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.i686-w64-mingw32.tar.gz"
[[Libassuan]]
arch = "powerpc64le"
git-tree-sha1 = "693a529a235bc54855c410b97c0c91830de6b4de"
libc = "glibc"
os = "linux"

    [[Libassuan.download]]
    sha256 = "a9474765b7d4951db025881158fb369a7bcb22fc2b1ed0e8a841dc867ca8ec44"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.powerpc64le-linux-gnu.tar.gz"
[[Libassuan]]
arch = "x86_64"
git-tree-sha1 = "806d1c28588eb4e72fc4af932d32e3ab119c169d"
os = "macos"

    [[Libassuan.download]]
    sha256 = "8f9457e24dda116e2f222dc7a5692a52ff12c60850e6b6e6c70c1660546bc511"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.x86_64-apple-darwin.tar.gz"
[[Libassuan]]
arch = "x86_64"
git-tree-sha1 = "f7ae1360fa4db7105801d77252b3dc72f9b0dff3"
libc = "glibc"
os = "linux"

    [[Libassuan.download]]
    sha256 = "94dc801e45394d6afb1ed2175cf6badee6de9dd89c699ffc331266560fa40b67"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.x86_64-linux-gnu.tar.gz"
[[Libassuan]]
arch = "x86_64"
git-tree-sha1 = "b445612791a2b43e69eb6e7595571fd72191707c"
libc = "musl"
os = "linux"

    [[Libassuan.download]]
    sha256 = "6a51c98df6820c56dc74c56015685da6137b6198760753a30a1ee9146c84e7cf"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.x86_64-linux-musl.tar.gz"
[[Libassuan]]
arch = "x86_64"
git-tree-sha1 = "818579dcac6acb03cbf42b286ed955a048da28d1"
os = "freebsd"

    [[Libassuan.download]]
    sha256 = "7c2fd29796886676c44f4c1152e311392077e4fcd5e5eaf11d7ecd8b68add16b"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.x86_64-unknown-freebsd.tar.gz"
[[Libassuan]]
arch = "x86_64"
git-tree-sha1 = "1ebb5bf97e78617a46ffe93f2ed25c04dd9e2dac"
os = "windows"

    [[Libassuan.download]]
    sha256 = "922f92d027976e743b487b32b2e10113488037ee7a46284cff8abffb407e6d31"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.5+1/Libassuan.v2.5.5.x86_64-w64-mingw32.tar.gz"
