[[Libassuan]]
arch = "aarch64"
git-tree-sha1 = "c6dd8440b3c9bddfc950fe1b5b2a2ab3b240312a"
os = "macos"

    [[Libassuan.download]]
    sha256 = "124cef893eaf28cb1f7f30cabc9372467e4e91e19dcb6b064a6b65a6e8bbafa4"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.aarch64-apple-darwin.tar.gz"
[[Libassuan]]
arch = "aarch64"
git-tree-sha1 = "7ca82e9cf4913907e5878c66e5b2e10b9bd3e604"
libc = "glibc"
os = "linux"

    [[Libassuan.download]]
    sha256 = "cff3e068054f11c21839ea7fa5c18d5eab883e8ccfd013848b645686cbecefc3"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.aarch64-linux-gnu.tar.gz"
[[Libassuan]]
arch = "aarch64"
git-tree-sha1 = "86d996225adfdccfe920759f32c893503f36e2b7"
libc = "musl"
os = "linux"

    [[Libassuan.download]]
    sha256 = "b2d2f415992e2db82745bdb76cc1de36005b1e3d46e7d3bd6a6daea6ae9001b3"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.aarch64-linux-musl.tar.gz"
[[Libassuan]]
arch = "aarch64"
git-tree-sha1 = "406e6fbade2425d21a75549c7d9714e0bc248dcf"
os = "freebsd"

    [[Libassuan.download]]
    sha256 = "7e4d0587e8022be1285850cccfeef04f721ab909ccf4abed4946607a0108f07e"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.aarch64-unknown-freebsd.tar.gz"
[[Libassuan]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "940b902037d9f669465235c34b953424033e910e"
libc = "glibc"
os = "linux"

    [[Libassuan.download]]
    sha256 = "851250356103f94e16ac7dc531dba9c791e3c59faca3a5a3b6b950de33166823"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.armv6l-linux-gnueabihf.tar.gz"
[[Libassuan]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e617e52b59079589a87c80da5f5fee309d07501b"
libc = "musl"
os = "linux"

    [[Libassuan.download]]
    sha256 = "5d7286ea2c69560b4624704e40d7e6239c5b16a774e4b8d888ba0d5e5781d63f"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.armv6l-linux-musleabihf.tar.gz"
[[Libassuan]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bfc86a7fa4fb779579af50ddc9b5e2a8da5e3260"
libc = "glibc"
os = "linux"

    [[Libassuan.download]]
    sha256 = "bea25d341b7c39ba2e0c987919171b4a93b1f2382295e4b48e59e1da4a89174d"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.armv7l-linux-gnueabihf.tar.gz"
[[Libassuan]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bf5602e9f5d31aaba2858050226b4e8b6ed478e0"
libc = "musl"
os = "linux"

    [[Libassuan.download]]
    sha256 = "d3111a142124524d2acf7f103ba8d6d3e888ef9489e682cef3065f91d6159f44"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.armv7l-linux-musleabihf.tar.gz"
[[Libassuan]]
arch = "i686"
git-tree-sha1 = "2d059027b081d527ea8f0d5f81b2eb40b9f54ff1"
libc = "glibc"
os = "linux"

    [[Libassuan.download]]
    sha256 = "d06b0c7dea96b71c05d8a567fd361e00b8f4dfbc2ea9ecbc4e18d18023ae5f15"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.i686-linux-gnu.tar.gz"
[[Libassuan]]
arch = "i686"
git-tree-sha1 = "582076b14a9791a8026d651df9f6e73f9b563867"
libc = "musl"
os = "linux"

    [[Libassuan.download]]
    sha256 = "ae153acfc7989790d7f813168590c151037db22f05aa9b5d21c2b9164d9b1e02"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.i686-linux-musl.tar.gz"
[[Libassuan]]
arch = "i686"
git-tree-sha1 = "c383882d08a8a79127b98cfc57afba1e597ee7e4"
os = "windows"

    [[Libassuan.download]]
    sha256 = "8bfff28a380ffaed4234e19d99d7b5a22e465d47fbfc50c6f73a193053d67159"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.i686-w64-mingw32.tar.gz"
[[Libassuan]]
arch = "powerpc64le"
git-tree-sha1 = "88156c23e0b898ce64e5c0312194832337e2b6e3"
libc = "glibc"
os = "linux"

    [[Libassuan.download]]
    sha256 = "3b996248d9957ac47a93297e3898fe33a6096aef84a16b1280d44694b6a869c0"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.powerpc64le-linux-gnu.tar.gz"
[[Libassuan]]
arch = "x86_64"
git-tree-sha1 = "e7ca2bf1a792832d522a6b05b9997f2472dd6936"
os = "macos"

    [[Libassuan.download]]
    sha256 = "02b2a14ea26a6fc192748a0486516fd9a6550f970ef17741700d282509e110e8"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.x86_64-apple-darwin.tar.gz"
[[Libassuan]]
arch = "x86_64"
git-tree-sha1 = "f0485fbb413eb547a183673458529766bd314791"
libc = "glibc"
os = "linux"

    [[Libassuan.download]]
    sha256 = "952b11b9f1eb3f6d4adc76f2e56646d062dfb9caf96f5336813f1d29c106eede"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.x86_64-linux-gnu.tar.gz"
[[Libassuan]]
arch = "x86_64"
git-tree-sha1 = "06e5aa84460eb961e370d28e8ca5516294306d55"
libc = "musl"
os = "linux"

    [[Libassuan.download]]
    sha256 = "93f1e48e71c5d47801daaee5245200fc03ec2e3c2dc73b2e74e7e99e08fd4030"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.x86_64-linux-musl.tar.gz"
[[Libassuan]]
arch = "x86_64"
git-tree-sha1 = "2ccc53a30ac0538881dc3016d4be4d0d0f1c7bc6"
os = "freebsd"

    [[Libassuan.download]]
    sha256 = "64b40a57fbc59d656cc6c92b16fe69ff32702c832ce532c3990a50c0afbe6825"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.x86_64-unknown-freebsd.tar.gz"
[[Libassuan]]
arch = "x86_64"
git-tree-sha1 = "7cf5bda0707ff1250c2e332e49cf970cad790b8b"
os = "windows"

    [[Libassuan.download]]
    sha256 = "9900517387d6862766fcc849d15a7a3d3d0808006403673da9b448cfe24a9788"
    url = "https://github.com/JuliaBinaryWrappers/Libassuan_jll.jl/releases/download/Libassuan-v2.5.7+0/Libassuan.v2.5.7.x86_64-w64-mingw32.tar.gz"
