# Autogenerated wrapper script for Libassuan_jll for i686-linux-musl
export libassuan

using Libgpg_error_jll
JLLWrappers.@generate_wrapper_header("Libassuan")
JLLWrappers.@declare_library_product(libassuan, "libassuan.so.0")
function __init__()
    JLLWrappers.@generate_init_header(Libgpg_error_jll)
    JLLWrappers.@init_library_product(
        libassuan,
        "lib/libassuan.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
