# Autogenerated wrapper script for Libassuan_jll for x86_64-w64-mingw32
export libassuan

using Libgpg_error_jll
JLLWrappers.@generate_wrapper_header("Libassuan")
JLLWrappers.@declare_library_product(libassuan, "libassuan-0.dll")
function __init__()
    JLLWrappers.@generate_init_header(Libgpg_error_jll)
    JLLWrappers.@init_library_product(
        libassuan,
        "bin\\libassuan-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
